#include <pwd.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <errno.h>
#include <netdb.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <string.h>
#include <fcntl.h>
#include <ctype.h>
#include "echo.h"
#include "cd.h"
#include "history.h"
#include "ls.h"
#include <signal.h>
#include <dirent.h>
#include <grp.h>
#include <time.h>
#include "pinfo.h"
#include "discover.h"
#include "fg.h"
#include <sys/wait.h>
#include "jobs.h"
#include "execute.h"
#include "commands.h"
